### ISSUE TITLE
Assozialles Restructuring V2 (Tracking Issue)

### ISSUE THREAD

**Issue by jonsch318** [htwr-aachen/htwr-aachen.de#44]
Nun bald ist es soweit...

Lange dran gearbeitet und so langsam muss es fertig sein, um der Bachelorarbeit weichen zu können. 

Die gesamte Restrukturierung soll bezwecken leichter neue Fächer hinzuzufügen und insgesamt verständlicher mithelfen zu können. Die Hilfe brauche ich nämlich immer mehr fortan.

Folgende Dinge (sind schon) werden gemacht:
- [x] ein Modernes Layout
- [ ] Modernes Layout mit automatischer Mobile Version.
- [x] Panikzettelseite Rebuild
- [x] docs Dokumentationsseite 
- [x] docs guides
- [x] blog
- [x] blog status bar Anbindung 
 
Folgendes wird für ein besseres Bearbeiten Verändert:
- [x] genauer definierte Nomenklatur
- [x] genauere Definition der URL Api
- [x] config directory mit zentralen Einstellungen für subjects und institutes
- [x] verschieben der navbar configs in die Institutes config.ts/navbar.ts
- [x] BasicSubjectInfo component für Folien-merge und panikzettel (erweiterbar)
- [x] (Subject)DocumentList als Standard collapsible tree view für Materialen
- [x] Trennung zwischen content-assets und teaching/summary-assers
- [x] Umbenennung teaching-assets -> summary-assets
- [x] Umwandeln aller Fächer
- [x] ExamInfo component 
- [x] FachSelection component

**Comment by jonsch318** [comment]
💀💀💀

<details>
```
On branch docs
Your branch is up to date with 'origin/docs'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .eslintrc
	modified:   package.json
	modified:   pnpm-lock.yaml
	modified:   public/sitemap-0.xml
	deleted:    src/app/admin/page.tsx
	modified:   src/app/api/teachings/route.ts
	modified:   src/app/botmein/botmein.module.scss
	modified:   src/app/botmein/page.tsx
	modified:   src/app/cesti/layout.tsx
	deleted:    src/app/cesti/studium/material/page.tsx
	deleted:    src/app/cesti/studium/page.tsx
	deleted:    src/app/cesti/studium/teachings/[...slug]/error.tsx
	deleted:    src/app/cesti/studium/teachings/[...slug]/page.tsx
	deleted:    src/app/cesti/studium/teachings/page.tsx
	modified:   src/app/cigol/klausuren/page.tsx
	modified:   src/app/cigol/layout.tsx
	modified:   src/app/cigol/studium/teachings/[...slug]/page.tsx
	modified:   src/app/cigol/studium/teachings/page.tsx
	deleted:    src/app/contact/page.tsx
	modified:   src/app/datenschutz/page.tsx
	modified:   src/app/deddebme/layout.tsx
	modified:   src/app/deddebme/lehre/page.tsx
	modified:   src/app/deddebme/lehre/teachings/[...slug]/page.tsx
	modified:   src/app/deddebme/lehre/teachings/page.tsx
	deleted:    src/app/docs/guides/high-performer/page.mdx
	deleted:    src/app/docs/guides/page.mdx
	modified:   src/app/docs/layout.tsx
	modified:   src/app/docs/nav.tsx
	modified:   src/app/docs/page.tsx
	deleted:    src/app/docs/switch.tsx
	modified:   src/app/es/layout.tsx
	modified:   src/app/es/studium/klausuren/page.tsx
	modified:   src/app/es/studium/teachings/[...slug]/page.tsx
	modified:   src/app/es/studium/teachings/page.tsx
	deleted:    src/app/impressum/page.tsx
	modified:   src/app/jobs/page.tsx
	modified:   src/app/layout.tsx
	modified:   src/app/male/layout.tsx
	modified:   src/app/male/teachings/[...slug]/page.tsx
	modified:   src/app/male/teachings/page.tsx
	deleted:    src/app/nichts/back.tsx
	deleted:    src/app/nichts/page.tsx
	modified:   src/app/not-found.tsx
	modified:   src/app/page.tsx
	modified:   src/app/panikzettel/page-anim/panikzettel-page.tsx
	deleted:    src/app/panikzettel/page-old.tsx
	modified:   src/app/panikzettel/page.tsx
	modified:   src/app/protected-download/page.tsx
	modified:   src/app/protected-download/protected-download.tsx
	modified:   src/app/scil/layout.tsx
	modified:   src/app/scil/studium/klausuren/page.tsx
	modified:   src/app/scil/studium/teachings/[...slug]/page.tsx
	modified:   src/app/scil/studium/teachings/page.tsx
	modified:   src/app/sibd/layout.tsx
	modified:   src/app/sibd/page.tsx
	modified:   src/app/sibd/scheduler/scheduler.tsx
	modified:   src/app/sibd/studium/klausuren/page.tsx
	deleted:    src/app/sibd/studium/teachings/[...slug]/error.tsx
	deleted:    src/app/sibd/studium/teachings/[...slug]/page.tsx
	modified:   src/app/sibd/studium/teachings/page.tsx
	modified:   src/app/syscom/comsys.rwth-aachen.de.tsx
	modified:   src/app/syscom/layout.tsx
	modified:   src/app/syscom/studium/teachings/[...slug]/page.tsx
	modified:   src/app/syscom/studium/teachings/page.tsx
	modified:   src/app/updates/page.mdx
	modified:   src/app/wsi/layout.tsx
	modified:   src/app/wsi/studium/klausuren/page.tsx
	modified:   src/app/wsi/studium/teachings/[...slug]/page.tsx
	modified:   src/app/wsi/studium/teachings/page.tsx
	deleted:    src/components/CommentSection.tsx
	modified:   src/components/InstituteSwitches.tsx
	deleted:    src/components/RumpeQuiz.tsx
	deleted:    src/components/SolutionCalculator.tsx
	deleted:    src/components/isoosi.tsx
	modified:   src/components/rwth/gallery.tsx
	deleted:    src/components/spoiler.tsx
	modified:   src/components/teachings/Layout.tsx
	modified:   src/components/teachings/List.tsx
	deleted:    src/components/teachings/Quizes/Rossmanith.tsx
	modified:   src/components/teachings/View.tsx
	deleted:    src/components/tooltip.tsx
	modified:   src/components/ui/bento.tsx
	deleted:    src/data/institutes.ts
	deleted:    src/data/layout.ts
	deleted:    src/data/subjects.ts
	modified:   src/hooks/path.ts
	modified:   src/hooks/useInstituteConfig.tsx
	modified:   src/hooks/useInstituteSearch.tsx
	deleted:    src/layouts/AppMain.tsx
	deleted:    src/layouts/Main.tsx
	deleted:    src/layouts/Meta.test.tsx
	deleted:    src/layouts/Meta.tsx
	modified:   src/layouts/SharedPushNotify.tsx
	modified:   src/layouts/cigol/Main.tsx
	modified:   src/layouts/cigol/sidenav.tsx
	modified:   src/layouts/deddebme/Main.tsx
	deleted:    src/layouts/deddebme/Navbar.tsx
	deleted:    src/layouts/deddebme/Sidenav.tsx
	modified:   src/layouts/es/Main.tsx
	deleted:    src/layouts/es/Meta.tsx
	modified:   src/layouts/es/Navbar.tsx
	modified:   src/layouts/es/Navlink.tsx
	deleted:    src/layouts/faculties-nav/breadcrumb.tsx
	deleted:    src/layouts/faculties-nav/desktop.tsx
	deleted:    src/layouts/faculties-nav/heading.tsx
	deleted:    src/layouts/faculties-nav/index.tsx
	deleted:    src/layouts/faculties-nav/institutes.tsx
	deleted:    src/layouts/faculties-nav/mobile.tsx
	deleted:    src/layouts/faculties-nav/nav-link.tsx
	deleted:    src/layouts/faculties-nav/nav.ts
	modified:   src/layouts/modern/nav/nav.tsx
	deleted:    src/layouts/rwth/DesktopNavbar.tsx
	modified:   src/layouts/rwth/Footer.tsx
	modified:   src/layouts/rwth/Main.tsx
	deleted:    src/layouts/rwth/MenuButton.tsx
	deleted:    src/layouts/rwth/Navbar.tsx
	deleted:    src/layouts/rwth/Sidenav.tsx
	deleted:    src/layouts/rwth/SidenavButton.tsx
	modified:   src/layouts/syscom/Main.tsx
	modified:   src/layouts/syscom/Navbar.tsx
	modified:   src/lib/documents.ts
	modified:   src/lib/institutes.ts
	modified:   src/lib/subjects.ts
	deleted:    src/lib/teaching.ts
	modified:   src/mdx-components.tsx
	modified:   src/models/institutes.ts
	modified:   src/models/layout.ts
	modified:   src/models/subject.ts
	modified:   src/styles/global.css
	modified:   tailwind.config.ts
	modified:   teachings/sibd/dbis/Entwurfstheorie.mdx

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	1
	__mocks__/fs.js
	__mocks__/fs/
	docs/
	public/content-assets/
	src/app/(generic)/
	src/app/_%institutename%/
	src/app/cesti/config.ts
	src/app/cesti/itsec/
	src/app/cesti/navbar.ts
	src/app/cigol/config.ts
	src/app/deddebme/config.ts
	src/app/deddebme/navbar.ts
	src/app/docs/[...slug]/
	src/app/docs/docsconfig.ts
	src/app/docs/local-icons.tsx
	src/app/es/config.ts
	src/app/male/config.ts
	src/app/male/navbar.ts
	src/app/navbar.ts
	src/app/scil/config.ts
	src/app/scil/navbar.ts
	src/app/sibd/config.ts
	src/app/sibd/dbis/
	src/app/sibd/navbar.ts
	src/app/syscom/navbar.ts
	src/app/updates/layout.tsx
	src/app/wsi/config.ts
	src/app/wsi/navbar.ts
	src/components/documents/
	src/components/exams/
	src/components/faculties-nav/
	src/components/icons/README.md
	src/components/teachings/isoosi.tsx
	src/components/teachings/quizes/
	src/components/teachings/solution-calculator.tsx
	src/components/teachings/spoiler.tsx
	src/components/ui/breadcrumb.tsx
	src/components/ui/button.tsx
	src/components/ui/drawer.tsx
	src/components/ui/sheet.tsx
	src/config/
	src/layouts/deddebme/default-navbar.ts
	src/layouts/deddebme/navbar/
	src/layouts/rwth/navbar/
	src/lib/article-metadata.test.ts
	src/lib/article-metadata.ts
	src/lib/articles.ts
	src/lib/exams.ts
	src/lib/panikzettel.ts
	src/lib/summaries.ts
	src/models/corpus.ts

no changes added to commit (use "git add" and/or "git commit -a")
```
</details>

**Comment by jonsch318** [comment]
Not all details are implemented. But most are now online
